#!/bin/bash

if [[ $# -ne 1  &&  $# -ne 2 ]]
then	
   echo "Usage: $0 word"

   echo "      Speak and Search: $0 -s word"

   echo "      Only Speak: $0 -v word"
   exit 1
fi

cd $STARDICT_HOME

if [ "$1" == "-s" ]
then
    which espeak >/dev/null 2>&1  && espeak -s 130 -ven+f3 "$2" &

    stardict.exe "$2" | more
elif [ "$1" == "-v" ]
then
    which espeak >/dev/null 2>&1 
    if [ $? -eq 0 ]
    then
        espeak -s 130 -ven+f3 "$2" &
    else
        echo "Install espeak please"
    fi
else
    stardict.exe "$1" | more
fi

