#!/bin/bash

if [[ $# -ne 1  &&  $# -ne 2 ]]
then	
   echo "Usage: $0 word"

   echo "Usage Speak the word, give the voice: $0 -s word"
   exit 1
fi

cd $STARDICT_HOME

if [ "$1" == "-s" ]
then
    which espeak 2>&1 >/dev/null  && espeak -s 130 -ven+f3 "$2" &

    stardict.exe $2 | more
else
    stardict.exe $1 | more
fi

